"""Added season column to the competition table

Revision ID: 10a05b116977
Revises: 7d9f1a133ec6
Create Date: 2025-10-18 20:31:31.492782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a05b116977'
down_revision: Union[str, Sequence[str], None] = '7d9f1a133ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('season', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'season')
    # ### end Alembic commands ###
