"""added timezone to the kickoff time in Fixture table

Revision ID: 118ef113bb3c
Revises: 339e8d5ccc92
Create Date: 2025-10-18 22:21:25.031079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118ef113bb3c'
down_revision: Union[str, Sequence[str], None] = '339e8d5ccc92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
