"""Added competition_id as a foreign key into the Pick DB

Revision ID: 2877c2d09ccc
Revises: 11dd86aa5169
Create Date: 2025-11-11 22:38:30.760020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2877c2d09ccc'
down_revision: Union[str, Sequence[str], None] = '11dd86aa5169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picks', sa.Column('competition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'picks', 'competitions', ['competition_id'], ['id'])
    op.alter_column('pool_user_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pool_user_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'picks', type_='foreignkey')
    op.drop_column('picks', 'competition_id')
    # ### end Alembic commands ###
