"""Added addditional columns to the fixture table : External ID

Revision ID: 339e8d5ccc92
Revises: 60404a5125fe
Create Date: 2025-10-18 21:51:36.843148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339e8d5ccc92'
down_revision: Union[str, Sequence[str], None] = '60404a5125fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('external_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'fixtures', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fixtures', type_='unique')
    op.drop_column('fixtures', 'external_id')
    # ### end Alembic commands ###
