"""Added participation count property to get number of users in a pool

Revision ID: 37cb853773cd
Revises: 40c48ede3650
Create Date: 2025-12-06 19:49:45.498028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cb853773cd'
down_revision: Union[str, Sequence[str], None] = '40c48ede3650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pools', 'session_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pools', 'competition_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pools', 'competition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pools', 'session_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
