"""Added session_code to the Pools table. Also documneted the creator of the pool and made them the admin.

Revision ID: 40c48ede3650
Revises: 1ba7c9c48e63
Create Date: 2025-12-01 00:10:36.744593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c48ede3650'
down_revision: Union[str, Sequence[str], None] = '1ba7c9c48e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pools', sa.Column('session_code', sa.String(), nullable=True))
    op.add_column('pools', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'pools', ['session_code'])
    op.create_foreign_key(None, 'pools', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pools', type_='foreignkey')
    op.drop_constraint(None, 'pools', type_='unique')
    op.drop_column('pools', 'created_by')
    op.drop_column('pools', 'session_code')
    # ### end Alembic commands ###
