"""Added addditional columns to the fixture table: status,home_goals, away_goals, referree, updated_at

Revision ID: 60404a5125fe
Revises: 10a05b116977
Create Date: 2025-10-18 21:17:03.973248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60404a5125fe'
down_revision: Union[str, Sequence[str], None] = '10a05b116977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('status', sa.String(), nullable=True))
    op.add_column('fixtures', sa.Column('home_goals', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('away_goals', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('referee', sa.String(), nullable=True))
    op.add_column('fixtures', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'updated_at')
    op.drop_column('fixtures', 'referee')
    op.drop_column('fixtures', 'away_goals')
    op.drop_column('fixtures', 'home_goals')
    op.drop_column('fixtures', 'status')
    # ### end Alembic commands ###
