"""Add external_id to teams

Revision ID: 69a2d0b2f33a
Revises: 44de7860fe4d
Create Date: 2025-10-15 23:35:22.318545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a2d0b2f33a'
down_revision: Union[str, Sequence[str], None] = '44de7860fe4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('external_id', sa.Integer(), nullable=False))
    op.add_column('teams', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('venue_name', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'teams', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'created_at')
    op.drop_column('teams', 'venue_name')
    op.drop_column('teams', 'short_name')
    op.drop_column('teams', 'external_id')
    # ### end Alembic commands ###
