"""Revert competition FK to id

Revision ID: 7d9f1a133ec6
Revises: f0d99d198408
Create Date: 2025-10-18 20:08:55.405956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9f1a133ec6'
down_revision: Union[str, Sequence[str], None] = 'f0d99d198408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teams_competition_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'competitions', ['competition_id'], ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_competition_id_fkey'), 'teams', 'competitions', ['competition_id'], ['id'])
    # ### end Alembic commands ###
