"""Add logo column to the teams Table to store url of a teams logo

Revision ID: 997167814348
Revises: cde248d8056e
Create Date: 2025-11-27 18:05:47.900182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997167814348'
down_revision: Union[str, Sequence[str], None] = 'cde248d8056e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'logo')
    # ### end Alembic commands ###
