"""Added team_id into the Picks table

Revision ID: ae958f82df21
Revises: 6871eb0eae0e
Create Date: 2025-11-06 15:38:41.943445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae958f82df21'
down_revision: Union[str, Sequence[str], None] = '6871eb0eae0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picks', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'picks', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'picks', type_='foreignkey')
    op.drop_column('picks', 'team_id')
    # ### end Alembic commands ###
