"""Add external_id to competition table

Revision ID: c8d4110d9140
Revises: 69a2d0b2f33a
Create Date: 2025-10-16 22:07:33.012511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d4110d9140'
down_revision: Union[str, Sequence[str], None] = '69a2d0b2f33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('external_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'competitions', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitions', type_='unique')
    op.drop_column('competitions', 'external_id')
    # ### end Alembic commands ###
