"""Add points and total_points columns to the pick and PUS tables

Revision ID: cde248d8056e
Revises: 2877c2d09ccc
Create Date: 2025-11-12 22:33:26.160314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde248d8056e'
down_revision: Union[str, Sequence[str], None] = '2877c2d09ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picks', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('pool_user_stats', sa.Column('total_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool_user_stats', 'total_points')
    op.drop_column('picks', 'points')
    # ### end Alembic commands ###
