"""Add more columns to the Competition table : type, logo, created_at, updated_at 

Revision ID: f0d99d198408
Revises: c8d4110d9140
Create Date: 2025-10-18 19:42:18.629876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d99d198408'
down_revision: Union[str, Sequence[str], None] = 'c8d4110d9140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('type', sa.String(), nullable=True))
    op.add_column('competitions', sa.Column('logo', sa.String(), nullable=True))
    op.add_column('competitions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('competitions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'updated_at')
    op.drop_column('competitions', 'created_at')
    op.drop_column('competitions', 'logo')
    op.drop_column('competitions', 'type')
    # ### end Alembic commands ###
