import { StyleSheet } from 'react-native';

export const createStyles = (colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  loadingText: {
    color: colors.textMuted,
    marginTop: 16,
    fontSize: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 50,
    paddingBottom: 16,
    paddingHorizontal: 16,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.inputBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerCenter: {
    flex: 1,
    marginHorizontal: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  headerSubtitle: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  livesIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.heart + '20',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 4,
  },
  livesText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.heart,
  },
  tabBar: {
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tabBarContent: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
  },
  tabButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: colors.inputBackground,
    gap: 6,
  },
  tabButtonActive: {
    backgroundColor: colors.accent,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
  },
  tabTextActive: {
    color: colors.textOnAccent,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  // Summary Tab Styles
  deadlineCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warning + '15',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.warning + '30',
  },
  deadlineIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.warning + '20',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deadlineContent: {
    flex: 1,
    marginLeft: 12,
  },
  deadlineLabel: {
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: 2,
  },
  deadlineTime: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.warning,
  },
  deadlineButton: {
    backgroundColor: colors.accent,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  deadlineButtonText: {
    color: colors.textOnAccent,
    fontSize: 13,
    fontWeight: '700',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  statsCard: {
    width: '47%',
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  livesDisplay: {
    flexDirection: 'row',
    gap: 4,
    marginBottom: 8,
  },
  statsValue: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  statsLabel: {
    fontSize: 11,
    color: colors.textMuted,
    textTransform: 'uppercase',
  },
  recentPickCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  seeAllText: {
    fontSize: 13,
    color: colors.accent,
    fontWeight: '600',
  },
  recentPickContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  teamBadge: {
    backgroundColor: colors.accent + '20',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  teamBadgeText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.accent,
  },
  recentPickWeek: {
    fontSize: 13,
    color: colors.textMuted,
  },
  leaderboardPreview: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  leaderboardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  rankBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.inputBackground,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  rankBadgeGold: {
    backgroundColor: '#FFD700',
  },
  rankText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  leaderboardName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  leaderboardLives: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  leaderboardLivesText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.heart,
  },
  // Make Pick Tab Styles
  pickHeader: {
    marginBottom: 20,
  },
  pickTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  pickSubtitle: {
    fontSize: 14,
    color: colors.textMuted,
  },
  teamsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  teamCard: {
    width: '47%',
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.border,
    position: 'relative',
  },
  teamCardSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accent + '10',
  },
  teamCardDisabled: {
    opacity: 0.5,
  },
  teamCardOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 1,
  },
  teamLogo: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.inputBackground,
    marginBottom: 8,
  },
  teamName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 4,
  },
  teamFixture: {
    fontSize: 11,
    color: colors.textMuted,
    textAlign: 'center',
  },
  usedBadge: {
    marginTop: 8,
    backgroundColor: colors.warning + '20',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  usedBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.warning,
  },
  selectedIndicator: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  confirmContainer: {
    marginTop: 20,
    paddingBottom: 20,
  },
  confirmButton: {
    backgroundColor: colors.accent,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  confirmButtonText: {
    color: colors.textOnAccent,
    fontSize: 16,
    fontWeight: '700',
  },
  // Standings Tab Styles
  standingsHeader: {
    marginBottom: 16,
  },
  standingsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  standingsSubtitle: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
  },
  standingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  standingsRowHighlight: {
    borderColor: colors.accent,
    backgroundColor: colors.accent + '10',
  },
  standingsRank: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.inputBackground,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  standingsRankGold: {
    backgroundColor: '#FFD700',
  },
  standingsRankSilver: {
    backgroundColor: '#C0C0C0',
  },
  standingsRankBronze: {
    backgroundColor: '#CD7F32',
  },
  standingsRankText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  standingsInfo: {
    flex: 1,
  },
  standingsName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  standingsNameHighlight: {
    color: colors.accent,
  },
  standingsPoints: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  standingsLives: {
    flexDirection: 'row',
    gap: 2,
  },
  // History Tab Styles
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  historyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  weekSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  weekButton: {
    padding: 8,
  },
  weekText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
    paddingHorizontal: 8,
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  historyUser: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  historyAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.accent + '30',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  historyAvatarText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.accent,
  },
  historyUsername: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  historyPick: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  historyTeam: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  historyResult: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.inputBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  historyResultWin: {
    backgroundColor: colors.success + '30',
  },
  historyResultLoss: {
    backgroundColor: colors.error + '30',
  },
  historyResultDraw: {
    backgroundColor: colors.warning + '30',
  },
  historyResultText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  historyNoPick: {
    fontSize: 13,
    color: colors.textMuted,
    fontStyle: 'italic',
  },
  historyFilterRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  historyFilterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  historyFilterButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  historyFilterText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
  },
  historyFilterTextActive: {
    color: colors.textOnAccent,
  },
  historySubtitle: {
    fontSize: 14,
    color: colors.textMuted,
    marginBottom: 16,
  },
  historyUserSelect: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  historyUserSelectInfo: {
    flex: 1,
  },
  historyUserSelectSub: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  historyBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
  },
  historyBackText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.accent,
  },
  historyUserHeader: {
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  historyAvatarLarge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.accent + '30',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  historyAvatarLargeText: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.accent,
  },
  historyUserName: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  historyUserStats: {
    fontSize: 13,
    color: colors.textMuted,
  },
  historyWeekRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  historyWeekBadge: {
    backgroundColor: colors.inputBackground,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    marginRight: 12,
  },
  historyWeekBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
  },
  historyWeekTeam: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  weekSelectorContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  // Standings column header styles
  standingsColumnHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 8,
  },
  columnHeaderText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  standingsStatText: {
    width: 50,
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  // Info Tab Styles
  infoCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  infoSubtitle: {
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: 12,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  infoText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  sessionCodeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderRadius: 12,
    padding: 16,
  },
  sessionCode: {
    flex: 1,
    fontSize: 24,
    fontWeight: '700',
    color: colors.accent,
    letterSpacing: 4,
    textAlign: 'center',
  },
  copyButton: {
    padding: 8,
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  memberAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.accent + '30',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  memberAvatarText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.accent,
  },
  memberName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  creatorBadge: {
    backgroundColor: colors.primary + '30',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  creatorBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.primary,
  },
});
